// import { Inter, Montserrat } from "next/font/google";
// // import { Montserrat } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
// const Montserrat = Montserrat({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={Montserrat.className}>{children}</body>
//     </html>
//   );
// }

import { Inter, Montserrat as MontserratFont } from "next/font/google"; // Renomeie a importação para evitar conflitos
import "./globals.css";

// Defina as fontes
const inter = Inter({ subsets: ["latin"] });
const montserrat = MontserratFont({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
